// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzySmU9gAu2PjbtDZb-awG5oKAuyCbsoY',
    appId: '1:646829897431:web:f4f98619eaa4aa40b7a292',
    messagingSenderId: '646829897431',
    projectId: 'infocheck-dc917',
    authDomain: 'infocheck-dc917.firebaseapp.com',
    storageBucket: 'infocheck-dc917.firebasestorage.app',
    measurementId: 'G-LZD7KMX885',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_aEDp7xSMgJAqsUH8XjWny4fncaHwxiM',
    appId: '1:646829897431:android:471cebdb17e10d5ab7a292',
    messagingSenderId: '646829897431',
    projectId: 'infocheck-dc917',
    storageBucket: 'infocheck-dc917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC28WMSbs28q1NtvPv7xXu2PtGwGKKA6Bs',
    appId: '1:646829897431:ios:ed2320e4261a71d4b7a292',
    messagingSenderId: '646829897431',
    projectId: 'infocheck-dc917',
    storageBucket: 'infocheck-dc917.firebasestorage.app',
    iosClientId:
        '646829897431-5t6gu9dnef7mqtgi34u075p5ch29ivdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.infochecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC28WMSbs28q1NtvPv7xXu2PtGwGKKA6Bs',
    appId: '1:646829897431:ios:ed2320e4261a71d4b7a292',
    messagingSenderId: '646829897431',
    projectId: 'infocheck-dc917',
    storageBucket: 'infocheck-dc917.firebasestorage.app',
    iosClientId:
        '646829897431-5t6gu9dnef7mqtgi34u075p5ch29ivdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.infochecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzySmU9gAu2PjbtDZb-awG5oKAuyCbsoY',
    appId: '1:646829897431:web:8bb6d1da72e166bbb7a292',
    messagingSenderId: '646829897431',
    projectId: 'infocheck-dc917',
    authDomain: 'infocheck-dc917.firebaseapp.com',
    storageBucket: 'infocheck-dc917.firebasestorage.app',
    measurementId: 'G-5KXP17CCJ5',
  );
}
